management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
#      base-path: /
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:mysql://svhw-mysql-01.cqu3h6tjnld7.ap-northeast-1.rds.amazonaws.com:3306/echo?characterEncoding=utf8&useSSL=false
    username: admin
    password: Admin!234
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      max-active: 1
  redis:
    database: 0
    host: svhw-redis.ya4sh7.ng.0001.apne1.cache.amazonaws.com
    port: 6379
    timeout: 6000
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 10
        min-idle: 2
mybatis:
  check-config-location: true
  config-location: classpath:mybatis/mybatis-config.xml


