apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-python 
  labels:
    app: echo-python 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: echo-python 
  template:
    metadata:
      labels:
        app: echo-python 
    spec:
      containers:
      - name: echo-python 
        image: 597377428377.dkr.ecr.us-east-2.amazonaws.com/echo-python:latest 
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: echo-python
  name: echo-python
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000 
  selector:
    app: echo-python
  type: LoadBalancer
