apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eksdemo1
  region: ap-northeast-1
managedNodeGroups:

  # - name: ng-ondemand
  #   privateNetworking: true
  #   minSize: 0
  #   maxSize: 3
  #   ssh:
  #     publicKeyName: keypair-tokyo-2024
  #   instanceType: t3.medium
  #   tags:
  #     Project: svhw
  #     auto-delete: "no"
      
  - name: ng-spot
    privateNetworking: true
    minSize: 0
    maxSize: 3
    spot: true
    ssh:
      publicKeyName: keypair-tokyo-2024
    instanceTypes:
      - c5.xlarge
      - c5a.xlarge
    tags:
      Project: svhw
      auto-delete: "no"

#   - name: ng-gpu-ondemand
#     privateNetworking: true
#     minSize: 0
#     maxSize: 3
#     ssh:
#       publicKeyName: keypair-tokyo-2024
#     instanceType: g4dn.xlarge
#     tags:
#       Project: svhw
#       auto-delete: "no"

# nodeGroups:
#   - name: ng-selfod
#     minSize: 2
#     maxSize: 2
#     privateNetworking: true
#     instanceType: t3.medium
#     tags:
#       Project: svhw
#       auto-delete: "no"